version: '3.8'

services:
  app:
    image: ghcr.io/martadams89/monzo-credit-card-pot-sync:latest
    container_name: monzo-sync
    restart: unless-stopped
    volumes:
      - ./conf:/app/instance
      - ./backups:/app/backups
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=change-this-in-production
      - BASE_URL=http://localhost:8000
      - MONZO_CLIENT_ID=your-monzo-client-id
      - MONZO_CLIENT_SECRET=your-monzo-client-secret
      - TRUELAYER_CLIENT_ID=your-truelayer-client-id
      - TRUELAYER_CLIENT_SECRET=your-truelayer-client-secret
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=user@example.com
      - MAIL_PASSWORD=mail-password
      - MAIL_DEFAULT_SENDER=noreply@example.com
      # Admin user credentials (remember to change these in production!)
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=change-this-in-production
      - ADMIN_CREATE_IF_NOT_EXISTS=true
