version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monzo-sync-dev
    restart: unless-stopped
    volumes:
      - ./conf:/app/instance
      - ./backups:/app/backups
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.wsgi:app
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key-please-change
      - BASE_URL=http://localhost:8000
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/instance/app.db
      - MONZO_CLIENT_ID=your-monzo-client-id
      - MONZO_CLIENT_SECRET=your-monzo-client-secret
      - TRUELAYER_CLIENT_ID=your-truelayer-client-id
      - TRUELAYER_CLIENT_SECRET=your-truelayer-client-secret
      - NOTIFICATION_EMAILS_ENABLED=true
      - ADMIN_EMAIL=admin@example.com
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USE_SSL=false
      - MAIL_USERNAME=user@example.com
      - MAIL_PASSWORD=mail-password
      - MAIL_DEFAULT_SENDER=noreply@example.com
      - LOG_LEVEL=DEBUG
      - BACKUP_DIRECTORY=backups
      - BACKUP_COUNT=5
    command: flask run --host=0.0.0.0 --port=8000
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"


